extends: default

rules:
  line-length:
    max: 150
    allow-non-breakable-words: true
    allow-non-breakable-inline-mappings: true
  truthy:
    allowed-values: ["true", "false", "yes", "no"]
    check-keys: false
  document-start: disable
  comments:
    min-spaces-from-content: 1
